//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeather.namnsdagarRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="namnsdagarRef.NamnsdagarSoap")]
    public interface NamnsdagarSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NamnsdagarMetod", ReplyAction="*")]
        MyWeather.namnsdagarRef.NamnsdagarMetodResponse NamnsdagarMetod(MyWeather.namnsdagarRef.NamnsdagarMetodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NamnsdagarMetod", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeather.namnsdagarRef.NamnsdagarMetodResponse> NamnsdagarMetodAsync(MyWeather.namnsdagarRef.NamnsdagarMetodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NamnsdagarMetodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NamnsdagarMetod", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.namnsdagarRef.NamnsdagarMetodRequestBody Body;
        
        public NamnsdagarMetodRequest() {
        }
        
        public NamnsdagarMetodRequest(MyWeather.namnsdagarRef.NamnsdagarMetodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NamnsdagarMetodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public NamnsdagarMetodRequestBody() {
        }
        
        public NamnsdagarMetodRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NamnsdagarMetodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NamnsdagarMetodResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.namnsdagarRef.NamnsdagarMetodResponseBody Body;
        
        public NamnsdagarMetodResponse() {
        }
        
        public NamnsdagarMetodResponse(MyWeather.namnsdagarRef.NamnsdagarMetodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NamnsdagarMetodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NamnsdagarMetodResult;
        
        public NamnsdagarMetodResponseBody() {
        }
        
        public NamnsdagarMetodResponseBody(string NamnsdagarMetodResult) {
            this.NamnsdagarMetodResult = NamnsdagarMetodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NamnsdagarSoapChannel : MyWeather.namnsdagarRef.NamnsdagarSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NamnsdagarSoapClient : System.ServiceModel.ClientBase<MyWeather.namnsdagarRef.NamnsdagarSoap>, MyWeather.namnsdagarRef.NamnsdagarSoap {
        
        public NamnsdagarSoapClient() {
        }
        
        public NamnsdagarSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NamnsdagarSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamnsdagarSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamnsdagarSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeather.namnsdagarRef.NamnsdagarMetodResponse MyWeather.namnsdagarRef.NamnsdagarSoap.NamnsdagarMetod(MyWeather.namnsdagarRef.NamnsdagarMetodRequest request) {
            return base.Channel.NamnsdagarMetod(request);
        }
        
        public string NamnsdagarMetod(string name) {
            MyWeather.namnsdagarRef.NamnsdagarMetodRequest inValue = new MyWeather.namnsdagarRef.NamnsdagarMetodRequest();
            inValue.Body = new MyWeather.namnsdagarRef.NamnsdagarMetodRequestBody();
            inValue.Body.name = name;
            MyWeather.namnsdagarRef.NamnsdagarMetodResponse retVal = ((MyWeather.namnsdagarRef.NamnsdagarSoap)(this)).NamnsdagarMetod(inValue);
            return retVal.Body.NamnsdagarMetodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeather.namnsdagarRef.NamnsdagarMetodResponse> MyWeather.namnsdagarRef.NamnsdagarSoap.NamnsdagarMetodAsync(MyWeather.namnsdagarRef.NamnsdagarMetodRequest request) {
            return base.Channel.NamnsdagarMetodAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeather.namnsdagarRef.NamnsdagarMetodResponse> NamnsdagarMetodAsync(string name) {
            MyWeather.namnsdagarRef.NamnsdagarMetodRequest inValue = new MyWeather.namnsdagarRef.NamnsdagarMetodRequest();
            inValue.Body = new MyWeather.namnsdagarRef.NamnsdagarMetodRequestBody();
            inValue.Body.name = name;
            return ((MyWeather.namnsdagarRef.NamnsdagarSoap)(this)).NamnsdagarMetodAsync(inValue);
        }
    }
}
