//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeather.MovieFromYearRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieFromYearRef.MovieFromYearSoap")]
    public interface MovieFromYearSoap {
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MovieFromYearMothod", ReplyAction="*")]
        MyWeather.MovieFromYearRef.MovieFromYearMothodResponse MovieFromYearMothod(MyWeather.MovieFromYearRef.MovieFromYearMothodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MovieFromYearMothod", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeather.MovieFromYearRef.MovieFromYearMothodResponse> MovieFromYearMothodAsync(MyWeather.MovieFromYearRef.MovieFromYearMothodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MovieFromYearMothodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MovieFromYearMothod", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.MovieFromYearRef.MovieFromYearMothodRequestBody Body;
        
        public MovieFromYearMothodRequest() {
        }
        
        public MovieFromYearMothodRequest(MyWeather.MovieFromYearRef.MovieFromYearMothodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MovieFromYearMothodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public MovieFromYearMothodRequestBody() {
        }
        
        public MovieFromYearMothodRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MovieFromYearMothodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MovieFromYearMothodResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.MovieFromYearRef.MovieFromYearMothodResponseBody Body;
        
        public MovieFromYearMothodResponse() {
        }
        
        public MovieFromYearMothodResponse(MyWeather.MovieFromYearRef.MovieFromYearMothodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MovieFromYearMothodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MovieFromYearMothodResult;
        
        public MovieFromYearMothodResponseBody() {
        }
        
        public MovieFromYearMothodResponseBody(string MovieFromYearMothodResult) {
            this.MovieFromYearMothodResult = MovieFromYearMothodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MovieFromYearSoapChannel : MyWeather.MovieFromYearRef.MovieFromYearSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieFromYearSoapClient : System.ServiceModel.ClientBase<MyWeather.MovieFromYearRef.MovieFromYearSoap>, MyWeather.MovieFromYearRef.MovieFromYearSoap {
        
        public MovieFromYearSoapClient() {
        }
        
        public MovieFromYearSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieFromYearSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieFromYearSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieFromYearSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeather.MovieFromYearRef.MovieFromYearMothodResponse MyWeather.MovieFromYearRef.MovieFromYearSoap.MovieFromYearMothod(MyWeather.MovieFromYearRef.MovieFromYearMothodRequest request) {
            return base.Channel.MovieFromYearMothod(request);
        }
        
        public string MovieFromYearMothod(string value) {
            MyWeather.MovieFromYearRef.MovieFromYearMothodRequest inValue = new MyWeather.MovieFromYearRef.MovieFromYearMothodRequest();
            inValue.Body = new MyWeather.MovieFromYearRef.MovieFromYearMothodRequestBody();
            inValue.Body.value = value;
            MyWeather.MovieFromYearRef.MovieFromYearMothodResponse retVal = ((MyWeather.MovieFromYearRef.MovieFromYearSoap)(this)).MovieFromYearMothod(inValue);
            return retVal.Body.MovieFromYearMothodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeather.MovieFromYearRef.MovieFromYearMothodResponse> MyWeather.MovieFromYearRef.MovieFromYearSoap.MovieFromYearMothodAsync(MyWeather.MovieFromYearRef.MovieFromYearMothodRequest request) {
            return base.Channel.MovieFromYearMothodAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeather.MovieFromYearRef.MovieFromYearMothodResponse> MovieFromYearMothodAsync(string value) {
            MyWeather.MovieFromYearRef.MovieFromYearMothodRequest inValue = new MyWeather.MovieFromYearRef.MovieFromYearMothodRequest();
            inValue.Body = new MyWeather.MovieFromYearRef.MovieFromYearMothodRequestBody();
            inValue.Body.value = value;
            return ((MyWeather.MovieFromYearRef.MovieFromYearSoap)(this)).MovieFromYearMothodAsync(inValue);
        }
    }
}
