//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeather.MovieFromYearRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieFromYearRef.MovieFromYearSoap")]
    public interface MovieFromYearSoap {
        
        // CODEGEN: Generating message contract since element name MovieFromYearMothod2012Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MovieFromYearMothod2012", ReplyAction="*")]
        MyWeather.MovieFromYearRef.MovieFromYearMothod2012Response MovieFromYearMothod2012(MyWeather.MovieFromYearRef.MovieFromYearMothod2012Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MovieFromYearMothod2012", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeather.MovieFromYearRef.MovieFromYearMothod2012Response> MovieFromYearMothod2012Async(MyWeather.MovieFromYearRef.MovieFromYearMothod2012Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MovieFromYearMothod2012Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MovieFromYearMothod2012", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.MovieFromYearRef.MovieFromYearMothod2012RequestBody Body;
        
        public MovieFromYearMothod2012Request() {
        }
        
        public MovieFromYearMothod2012Request(MyWeather.MovieFromYearRef.MovieFromYearMothod2012RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MovieFromYearMothod2012RequestBody {
        
        public MovieFromYearMothod2012RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MovieFromYearMothod2012Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MovieFromYearMothod2012Response", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.MovieFromYearRef.MovieFromYearMothod2012ResponseBody Body;
        
        public MovieFromYearMothod2012Response() {
        }
        
        public MovieFromYearMothod2012Response(MyWeather.MovieFromYearRef.MovieFromYearMothod2012ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MovieFromYearMothod2012ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MovieFromYearMothod2012Result;
        
        public MovieFromYearMothod2012ResponseBody() {
        }
        
        public MovieFromYearMothod2012ResponseBody(string MovieFromYearMothod2012Result) {
            this.MovieFromYearMothod2012Result = MovieFromYearMothod2012Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MovieFromYearSoapChannel : MyWeather.MovieFromYearRef.MovieFromYearSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieFromYearSoapClient : System.ServiceModel.ClientBase<MyWeather.MovieFromYearRef.MovieFromYearSoap>, MyWeather.MovieFromYearRef.MovieFromYearSoap {
        
        public MovieFromYearSoapClient() {
        }
        
        public MovieFromYearSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieFromYearSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieFromYearSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieFromYearSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeather.MovieFromYearRef.MovieFromYearMothod2012Response MyWeather.MovieFromYearRef.MovieFromYearSoap.MovieFromYearMothod2012(MyWeather.MovieFromYearRef.MovieFromYearMothod2012Request request) {
            return base.Channel.MovieFromYearMothod2012(request);
        }
        
        public string MovieFromYearMothod2012() {
            MyWeather.MovieFromYearRef.MovieFromYearMothod2012Request inValue = new MyWeather.MovieFromYearRef.MovieFromYearMothod2012Request();
            inValue.Body = new MyWeather.MovieFromYearRef.MovieFromYearMothod2012RequestBody();
            MyWeather.MovieFromYearRef.MovieFromYearMothod2012Response retVal = ((MyWeather.MovieFromYearRef.MovieFromYearSoap)(this)).MovieFromYearMothod2012(inValue);
            return retVal.Body.MovieFromYearMothod2012Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeather.MovieFromYearRef.MovieFromYearMothod2012Response> MyWeather.MovieFromYearRef.MovieFromYearSoap.MovieFromYearMothod2012Async(MyWeather.MovieFromYearRef.MovieFromYearMothod2012Request request) {
            return base.Channel.MovieFromYearMothod2012Async(request);
        }
        
        public System.Threading.Tasks.Task<MyWeather.MovieFromYearRef.MovieFromYearMothod2012Response> MovieFromYearMothod2012Async() {
            MyWeather.MovieFromYearRef.MovieFromYearMothod2012Request inValue = new MyWeather.MovieFromYearRef.MovieFromYearMothod2012Request();
            inValue.Body = new MyWeather.MovieFromYearRef.MovieFromYearMothod2012RequestBody();
            return ((MyWeather.MovieFromYearRef.MovieFromYearSoap)(this)).MovieFromYearMothod2012Async(inValue);
        }
    }
}
