//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeather.add2numbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="add2numbers.Adderar2TalSoap")]
    public interface Adderar2TalSoap {
        
        // CODEGEN: Generating message contract since element name tal1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlusaIhop", ReplyAction="*")]
        MyWeather.add2numbers.PlusaIhopResponse PlusaIhop(MyWeather.add2numbers.PlusaIhopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlusaIhop", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeather.add2numbers.PlusaIhopResponse> PlusaIhopAsync(MyWeather.add2numbers.PlusaIhopRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlusaIhopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlusaIhop", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.add2numbers.PlusaIhopRequestBody Body;
        
        public PlusaIhopRequest() {
        }
        
        public PlusaIhopRequest(MyWeather.add2numbers.PlusaIhopRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlusaIhopRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tal1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tal2;
        
        public PlusaIhopRequestBody() {
        }
        
        public PlusaIhopRequestBody(string tal1, string tal2) {
            this.tal1 = tal1;
            this.tal2 = tal2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlusaIhopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlusaIhopResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.add2numbers.PlusaIhopResponseBody Body;
        
        public PlusaIhopResponse() {
        }
        
        public PlusaIhopResponse(MyWeather.add2numbers.PlusaIhopResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlusaIhopResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlusaIhopResult;
        
        public PlusaIhopResponseBody() {
        }
        
        public PlusaIhopResponseBody(string PlusaIhopResult) {
            this.PlusaIhopResult = PlusaIhopResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Adderar2TalSoapChannel : MyWeather.add2numbers.Adderar2TalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Adderar2TalSoapClient : System.ServiceModel.ClientBase<MyWeather.add2numbers.Adderar2TalSoap>, MyWeather.add2numbers.Adderar2TalSoap {
        
        public Adderar2TalSoapClient() {
        }
        
        public Adderar2TalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Adderar2TalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Adderar2TalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Adderar2TalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeather.add2numbers.PlusaIhopResponse MyWeather.add2numbers.Adderar2TalSoap.PlusaIhop(MyWeather.add2numbers.PlusaIhopRequest request) {
            return base.Channel.PlusaIhop(request);
        }
        
        public string PlusaIhop(string tal1, string tal2) {
            MyWeather.add2numbers.PlusaIhopRequest inValue = new MyWeather.add2numbers.PlusaIhopRequest();
            inValue.Body = new MyWeather.add2numbers.PlusaIhopRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            MyWeather.add2numbers.PlusaIhopResponse retVal = ((MyWeather.add2numbers.Adderar2TalSoap)(this)).PlusaIhop(inValue);
            return retVal.Body.PlusaIhopResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeather.add2numbers.PlusaIhopResponse> MyWeather.add2numbers.Adderar2TalSoap.PlusaIhopAsync(MyWeather.add2numbers.PlusaIhopRequest request) {
            return base.Channel.PlusaIhopAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeather.add2numbers.PlusaIhopResponse> PlusaIhopAsync(string tal1, string tal2) {
            MyWeather.add2numbers.PlusaIhopRequest inValue = new MyWeather.add2numbers.PlusaIhopRequest();
            inValue.Body = new MyWeather.add2numbers.PlusaIhopRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            return ((MyWeather.add2numbers.Adderar2TalSoap)(this)).PlusaIhopAsync(inValue);
        }
    }
}
