//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeather.AdderarTreTalRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdderarTreTalRef.AdderaTreTalSoap")]
    public interface AdderaTreTalSoap {
        
        // CODEGEN: Generating message contract since element name tal1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdderaTreTalMetod", ReplyAction="*")]
        MyWeather.AdderarTreTalRef.AdderaTreTalMetodResponse AdderaTreTalMetod(MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdderaTreTalMetod", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeather.AdderarTreTalRef.AdderaTreTalMetodResponse> AdderaTreTalMetodAsync(MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdderaTreTalMetodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdderaTreTalMetod", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequestBody Body;
        
        public AdderaTreTalMetodRequest() {
        }
        
        public AdderaTreTalMetodRequest(MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdderaTreTalMetodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tal1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tal2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tal3;
        
        public AdderaTreTalMetodRequestBody() {
        }
        
        public AdderaTreTalMetodRequestBody(string tal1, string tal2, string tal3) {
            this.tal1 = tal1;
            this.tal2 = tal2;
            this.tal3 = tal3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdderaTreTalMetodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdderaTreTalMetodResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeather.AdderarTreTalRef.AdderaTreTalMetodResponseBody Body;
        
        public AdderaTreTalMetodResponse() {
        }
        
        public AdderaTreTalMetodResponse(MyWeather.AdderarTreTalRef.AdderaTreTalMetodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdderaTreTalMetodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdderaTreTalMetodResult;
        
        public AdderaTreTalMetodResponseBody() {
        }
        
        public AdderaTreTalMetodResponseBody(string AdderaTreTalMetodResult) {
            this.AdderaTreTalMetodResult = AdderaTreTalMetodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdderaTreTalSoapChannel : MyWeather.AdderarTreTalRef.AdderaTreTalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdderaTreTalSoapClient : System.ServiceModel.ClientBase<MyWeather.AdderarTreTalRef.AdderaTreTalSoap>, MyWeather.AdderarTreTalRef.AdderaTreTalSoap {
        
        public AdderaTreTalSoapClient() {
        }
        
        public AdderaTreTalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdderaTreTalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdderaTreTalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdderaTreTalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeather.AdderarTreTalRef.AdderaTreTalMetodResponse MyWeather.AdderarTreTalRef.AdderaTreTalSoap.AdderaTreTalMetod(MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequest request) {
            return base.Channel.AdderaTreTalMetod(request);
        }
        
        public string AdderaTreTalMetod(string tal1, string tal2, string tal3) {
            MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequest inValue = new MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequest();
            inValue.Body = new MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            inValue.Body.tal3 = tal3;
            MyWeather.AdderarTreTalRef.AdderaTreTalMetodResponse retVal = ((MyWeather.AdderarTreTalRef.AdderaTreTalSoap)(this)).AdderaTreTalMetod(inValue);
            return retVal.Body.AdderaTreTalMetodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeather.AdderarTreTalRef.AdderaTreTalMetodResponse> MyWeather.AdderarTreTalRef.AdderaTreTalSoap.AdderaTreTalMetodAsync(MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequest request) {
            return base.Channel.AdderaTreTalMetodAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeather.AdderarTreTalRef.AdderaTreTalMetodResponse> AdderaTreTalMetodAsync(string tal1, string tal2, string tal3) {
            MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequest inValue = new MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequest();
            inValue.Body = new MyWeather.AdderarTreTalRef.AdderaTreTalMetodRequestBody();
            inValue.Body.tal1 = tal1;
            inValue.Body.tal2 = tal2;
            inValue.Body.tal3 = tal3;
            return ((MyWeather.AdderarTreTalRef.AdderaTreTalSoap)(this)).AdderaTreTalMetodAsync(inValue);
        }
    }
}
